server:
  port: 9040

spring:
  application:
    name: user-management
  datasource:
    url: jdbc:h2:file:./app/adapters/user-management/db/userDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true