server:
  port: 9090

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:file:./app/adapters/order-service/db/orderDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

#Client urls
service-url:
  cart: http://localhost:9050/mycart/
  payment: http://localhost:9080