server:
  port: 9070

spring:
  application:
    name: product-catalog
  datasource:
    url: jdbc:h2:file:./app/adapters/product-catalog/db/productDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true