server:
  port: 9050

spring:
  application:
    name: cart-service
  datasource:
    url: jdbc:h2:file:./app/adapters/cart-service/db/cartDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

#Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true

#Client urls
product-catalog:
  url: http://localhost:9070