server:
  port: 8888

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive


  cloud:
    gateway:
      routes:
        - id: cart-service
          uri: http://localhost:9050
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1

        - id: order-service
          uri: http://localhost:9090
          predicates:
            - Path=/order/**
          #filters:
           # - StripPrefix=1


#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true

key:
  path: app/adapters/api-gateway/key.txt

user-management:
  url: http://localhost:9040

logging:
  level:
    org:
      springframework:
        web: DEBUG