server:
  port: 8888

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      routes:
        - id: cart-service
          uri: http://localhost:9050
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1


#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true