server:
  port: 9030

spring:
  application:
    name: event-bus
  datasource:
    url: jdbc:h2:file:./app/event-bus/db/eventDb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

#Eureka client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: true
    fetchRegistry: true